{{- if .Values.hf.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chen.fullname" . }}-hf
  labels:
    {{- include "chen.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.hf.token | quote }}
{{- end }}
